# Generated by Django 5.2.5 on 2025-08-16 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CtlCardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("https://www.tcdb.com", "Trading Card Database"),
                            ("https://tcgcsv.com", "TCGCSV"),
                            ("https://api.pokemontcg.io", "Pokémon TCG API"),
                            ("https://api.scryfall.com", "Scryfall API"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("published", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Card set",
                "verbose_name_plural": "Card sets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CtlRefCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("side", models.IntegerField(choices=[(1, "Front"), (2, "Back")])),
                ("image", models.ImageField(upload_to="ctlrefcard_image")),
                ("number", models.CharField(max_length=50)),
                ("variant", models.CharField(blank=True, max_length=50, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ctlcardset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference card",
                "verbose_name_plural": "Reference cards",
                "ordering": ["card_set", "name"],
            },
        ),
    ]
