# Generated by Django 5.2.5 on 2025-08-24 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CtlUserBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("task_id", models.UUIDField(blank=True, default=None, null=True)),
                (
                    "card_scans",
                    models.FileField(
                        upload_to="ctluserbatch__card_scans",
                        validators=[
                            core.models.validate_zip_file,
                            core.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "scan_order",
                    models.IntegerField(
                        choices=[
                            (1, "Front Only"),
                            (2, "Front & Back - Front First"),
                            (3, "Front & Back - Back First"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CtlUserCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(blank=True, default=None, null=True)),
                ("front", models.ImageField(upload_to="ctlusercard__front")),
                ("back", models.ImageField(null=True, upload_to="ctlusercard__back")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ctluserbatch",
                    ),
                ),
                (
                    "ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ctlrefcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "User card",
                "verbose_name_plural": "User cards",
                "ordering": ["ref__name"],
            },
        ),
    ]
