# Generated by Django 5.2.5 on 2025-08-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ctlusercard_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ctlusercard",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.ctluserbatch",
            ),
        ),
    ]
